### ISSUE TITLE
bug : Regarding book pdf "An Introduction to Object-Oriented Programming with Java.pdf"

### ISSUE THREAD

**Issue by RahulSharma2001** [dbc2201/GLAU_BCSC0002#3]
Sir, Book is not downloading.....LINK:https://github.com/dbc2201/GLAU_BCSC0002/blob/master/Books/An%20Introduction%20to%20Object-Oriented%20Programming%20with%20Java.pdf

**Comment by dbc2201** [comment]
@RahulSharma2001 
From the link that you have sent me, I can see that the link is working fine, there should be a download button situated above the book. The book might take some time to load, but you can skip it altogether and simply download the book by clicking on the button.

**Comment by RahulSharma2001** [comment]
Thank you sir
Now its working...
