### ISSUE TITLE
i am not able to take multiple inputs in my programme, i have gone through pdf on this topic but still did'nt got it . help ke out sir. 

### ISSUE THREAD

**Issue by vikaspandey07** [dbc2201/GLAU_BCSC0002#4]

**Comment by dbc2201** [comment]
You had to write 
```
"i am not able to take multiple inputs in my programme, i have gone through pdf on this topic but still did'nt got it . help ke out sir"
```
inside the text box.
anyhow, use [this](https://gist.github.com/) to upload your file. I'll check out the code.

**Comment by dbc2201** [comment]
Paste the URL of the file you wrote here

**Comment by vikaspandey07** [comment]
i sorted it out from the PDF of OOP you had earlier sent on group. thnkyou for your kind attention sir.
