### ISSUE TITLE
DOUBT REGARDING OUTPUT 

### ISSUE THREAD

**Issue by gfobiyatechnical** [dbc2201/GLAU_BCSC0002#7]
_

> Book Question of Hackerrank assigned at Google Classroom.

_
**My github link:** 
https://github.com/RakeshY008/Lab04/blob/master/GoogleClassRoom/src/Google_Class/Hackerrank.java

Note: I am not getting expected output at _'hackerrank'_  but for same test case i am getting correct output by  IntelliJ IDEA

**Comment by divaibhav** [comment]
Remove line no 19 --->  myObj.nextLine().trim();
